### ISSUE TITLE
Typo on the homepage

### ISSUE THREAD

**Issue by JanelleJohnson** [spyoungtech/spyoungtech.github.io#1]
The heading says "Spencre Young" when it should say "Spencer Young"

**Comment by spyoungtech** [comment]
Thanks for pointing that out @JanelleJohnson -- I may get around to this some time. Or, if you submit a pull request, I'll merge it in. 

Thanks!

**Comment by spyoungtech** [comment]
Fixed in Pull #2 

Closing.
